### ISSUE TITLE
Env in pod is not loading as expected

### ISSUE THREAD

**Issue by nihit-elsevier** [GoogleCloudPlatform/secrets-store-csi-driver-provider-gcp#356] opened 2023-11-09 04:11 UTC
I am using below secretproviderclass and it is creating secret and loading it as an env in pod but the format is not correct.

> `apiVersion: secrets-store.csi.x-k8s.io/v1
> kind: SecretProviderClass
> metadata:
>   name: pp-dev-pp-webapp
>   namespace: pp-dev
> spec:
>   provider: aws
>   secretObjects:
>   - secretName: csi-secret-newrelic
>     type: Opaque
>     data:
>     - key: NEW_RELIC_LICENSE_KEY
>       objectName: NEW_RELIC_LICENSE_KEY
>   parameters:
>     objects: |
>         - objectName: "arn:aws:secretsmanager:us-east-1:xxxxxxxxxxxxxxxxx"
>           objectAlias: "NEW_RELIC_LICENSE_KEY"
>           objectType: "secretsmanager"

`

> `
> .
> .
> .
> volumes:
>       - name: pod-webapp
>         csi:
>           driver: secrets-store.csi.k8s.io
>           readOnly: true
>           volumeAttributes:
>             secretProviderClass: "pp-dev-pp-webapp"
>       containers:
>         - name: {{ include "helm.name" . }}
>           image: {{ .Values.imageRepository }}/{{ .Values.imageName }}:{{ .Values.imageTag }}
>           imagePullPolicy: {{ .Values.imagePullPolicy }}
>           volumeMounts:
>            - name: pod-webapp
>              mountPath: "/mnt"
>              readOnly: true
>           env:
>           - name: test_name
>             valueFrom:
>               secretKeyRef:
>                 name: csi-secret-newrelic
>                 key: NEW_RELIC_LICENSE_KEY
> .
> .
> .
> `
> 

The env is loading in below format

test_name={"NEW_RELIC_LICENSE_KEY":"xxxxxxxxxxxxxxxx"}

but it should be in format

NEW_RELIC_LICENSE_KEY":"xxxxxxxxxxxxxxxx

**Comment by f0o** [comment] 2023-11-11 09:57
dupe of #357 ?

**Comment by NaMNDV** [comment] 2024-02-28 09:02
Thanks for reporting this issue! There does not seem to be any further action item on this issue and hence we are closing it. Please feel free to reopen this issue or file a new one if you need further assistance.

**Closed by NaMNDV** 2024-02-28 09:02 UTC
Labels: bug
